name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        flake8 analysis.py test_analysis.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 analysis.py test_analysis.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Format check with black
      run: |
        black --check analysis.py test_analysis.py
    
    - name: Test with pytest
      run: |
        pytest test_analysis.py -v --cov=analysis --cov-report=xml
    
    - name: Run main analysis
      run: |
        python analysis.py